// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDql8ke9p-98qo8BMUQT88URWW-mHtLQeY',
    appId: '1:366526035539:web:407f9b5496515e68d0f8a6',
    messagingSenderId: '366526035539',
    projectId: 'univenty-app',
    authDomain: 'univenty-app.firebaseapp.com',
    storageBucket: 'univenty-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_XxkYGBqEbDAQueOawOrRaSnuoH7Dsg0',
    appId: '1:366526035539:android:521809f9abb823afd0f8a6',
    messagingSenderId: '366526035539',
    projectId: 'univenty-app',
    storageBucket: 'univenty-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvULkeMP_rDRlIkydXo3JPXuv90ZvD0SQ',
    appId: '1:366526035539:ios:3149f827fcf6ef01d0f8a6',
    messagingSenderId: '366526035539',
    projectId: 'univenty-app',
    storageBucket: 'univenty-app.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvULkeMP_rDRlIkydXo3JPXuv90ZvD0SQ',
    appId: '1:366526035539:ios:70d057846ef47323d0f8a6',
    messagingSenderId: '366526035539',
    projectId: 'univenty-app',
    storageBucket: 'univenty-app.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
